language: android
android:
  components:
    - platform-tools
    - tools
    - android-22
install:
    - npm install
    - npm install -g cordova
    - npm install -g ionic
    - ionic platform add android
script:
    - mkdir ../sikher-dist/
    - ./build