#!/bin/sh

# Variables
PLATFORM=$1
ARCH=$2
VERSION=$3
ELECTRON=$4
APPNAME=$5

# Defaults
: ${PLATFORM:="all"}
: ${ARCH:="all"}
: ${VERSION:="1.0.2"}
: ${ELECTRON:="0.29.2"}
: ${APPNAME:="Sikher"}

# Status
echo "PLATFORM: $PLATFORM (options: all, linux, win32, darwin),\nPLATFORM TYPE: $ARCH (options: ia32 or x64),\nAPP VERSION: $VERSION,\nELECTRON VERSION: $ELECTRON,\nAPP NAME: $APPNAME"

# Create Packages
echo "Let's create the packages..."
`electron-packager ./ $APPNAME --platform=$PLATFORM --arch=$ARCH --version=$ELECTRON --out=./dist/ --icon=./resources/icon.png --app-bundle-id=$APPNAME --app-version=$VERSION --version-string.CompanyName="$APPNAME" --version-string.ProductName="$APPNAME" --version-string.ProductVersion="$VERSION" --prune --overwrite --asar`

# Zip Packages
echo "Let's zip up those packages now..."
`zip Sikher-linux-x64.zip ./dist/Sikher-linux-x64`
`zip Sikher-linux-ia32.zip ./dist/Sikher-linux-ia32`
`zip Sikher-win32-x64.zip ./dist/Sikher-win32-x64`
`zip Sikher-win32-ia32.zip ./dist/Sikher-win32-ia32`
`zip Sikher-darwin-x64.zip ./dist/Sikher-darwin-x64`
`zip Sikher-darwin-ia32.zip ./dist/Sikher-darwin-ia32`

