#!/bin/sh

# Variables
PLATFORM=$1
ARCH=$2
VERSION=$3
ELECTRON=$4
APPNAME=$5
OUT=$6

# Defaults
: ${PLATFORM:="all"}
: ${ARCH:="all"}
: ${VERSION:="1.0.3"}
: ${ELECTRON:="0.34.1"}
: ${APPNAME:="Sikher"}
: ${OUT:="../sikher-dist/"}

# First lets create an app release
cordova build --release

# Status
echo "PLATFORM: $PLATFORM (options: all, linux, win32, darwin),\nPLATFORM TYPE: $ARCH (options: ia32 or x64),\nAPP VERSION: $VERSION,\nELECTRON VERSION: $ELECTRON,\nAPP NAME: $APPNAME,\nOUTPUT TO: $OUT"

# Create Packages
echo "Let's create the packages..."
`electron-packager ./ $APPNAME --platform=$PLATFORM --arch=$ARCH --version=$ELECTRON --out=$OUT --icon=./resources/icon.png --app-bundle-id=$APPNAME --app-version=$VERSION --version-string.CompanyName="$APPNAME" --version-string.ProductName="$APPNAME" --version-string.ProductVersion="$VERSION" --prune --overwrite --asar --ignore="(platforms|hooks|plugins|node_modules)"`

# Zip Packages
#echo "Let's zip up those packages now..."
#cd "${OUT}"
#echo "Now in `pwd`"
#`zip Sikher-linux-64bit.zip Sikher-linux-x64/* > /dev/null 2>&1`
#`zip Sikher-linux-32bit.zip Sikher-linux-ia32/* > /dev/null 2>&1`
#`zip Sikher-windows-64bit.zip Sikher-win32-x64/* > /dev/null 2>&1`
#`zip Sikher-windows-32bit.zip Sikher-win32-ia32/* > /dev/null 2>&1`
#`zip Sikher-mac-64bit.zip Sikher-darwin-x64/* > /dev/null 2>&1`
#`zip Sikher-darwin-ia32.zip Sikher-darwin-ia32/* > /dev/null 2>&1`
#echo "Finished zipping packages!"
echo "We're done here :)"

